# Generated by Django 5.0 on 2023-12-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='author',
            new_name='user',
        ),
    ]
